Refactor token updates
bitwave-tv/bitwave pull request #324
Opened 2020-08-08 16:50 UTC by diingus

Gone are the days of copy-pasted `getTokenId()` or `getFreshTokenId()` definitions and calls.

Surprisingly, all token usage was for request done through Axios. Axios requests are now intercepted and the Authorization header is being injected. The auth token is also automatically refreshed on client-side.

Server-side token parsing-from-cookies is also possible, but the commit-to-store part of it is commented out. Should only commit when on auth-guarded pages, or pages that make little sense to cache.

Closes #321

2020-08-09 12:24 UTC, diingus commented
I remember thinking of an issue with this branch last night before falling asleep. It could have also been a dream :thinking: 

Give me a few to try remember it

2020-08-09 22:11 UTC, diingus commented
Likely a dream, since I can't seem to remember it, and I can't find it in code.

2020-08-16 00:51 UTC, DispatchCommit requested changes

2020-08-16 00:51 UTC, DispatchCommit commented on plugins/firebase.js
> +              user.getIdToken().then( async (idToken) => {
just noting that you can replace `.then()`'s with `await`'s but I'll handle that post merge.

2020-08-16 00:51 UTC, DispatchCommit commented on plugins/firebase.js
> +          Authorization: 'Bearer ' + idToken,
Should the header be added if the `idToken` is `null`?

2020-08-16 06:38 UTC, DispatchCommit approved these changes

2020-08-16 06:38 UTC, merged